"""create messages table

Revision ID: 79c26059b28d
Revises: ec00758a7838
Create Date: 2025-06-20 00:23:44.598098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c26059b28d'
down_revision = 'ec00758a7838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(length=100), nullable=False))
    op.add_column('messages', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
